import type { ImportCategory } from './types';

export const CRAWL_LIMITS = {
  maxPages: 40,
  maxDepth: 3,
  maxRedirects: 5,
  maxResponseBytes: 1_500_000,
  requestTimeoutMs: 10_000,
  minRequestGapMs: 250,
  maxRetries: 2,
  maxSitemapFiles: 8,
  maxSitemapUrls: 120,
  maxItemsPerCategory: 80,
  maxTextChars: 4_000,
  maxArticleChars: 8_000,
} as const;

export const SAMPLE_HOSPITAL_SITES = [
  { label: 'Apollo Hospitals', url: 'https://www.apollohospitals.com' },
  { label: 'Fortis Healthcare', url: 'https://www.fortishealthcare.com' },
  { label: 'Narayana Health', url: 'https://www.narayanahealth.org' },
  { label: 'Max Healthcare', url: 'https://www.maxhealthcare.in' },
  { label: 'Manipal Hospitals', url: 'https://www.manipalhospitals.com' },
] as const;

export const CATEGORY_LABELS: Record<ImportCategory, string> = {
  hospitalProfile: 'Hospital profile',
  departments: 'Departments',
  specialities: 'Specialities',
  centres: 'Centres',
  services: 'Services',
  packages: 'Packages',
  faqs: 'FAQs',
  facilities: 'Facilities',
  patientResources: 'Patient resources',
  insurance: 'Insurance',
  international: 'International patients',
  articles: 'Articles',
  news: 'News',
  testimonials: 'Testimonials',
};

export const DISCOVERY_PATH_HINTS = [
  'department',
  'departments',
  'specialit',
  'specialty',
  'specialities',
  'specialties',
  'service',
  'services',
  'centre',
  'center',
  'centres',
  'centers',
  'excellence',
  'package',
  'packages',
  'health-check',
  'health-checkup',
  'healthcheckup',
  'faq',
  'faqs',
  'facility',
  'facilities',
  'patient-care',
  'patient-resource',
  'patient-resources',
  'insurance',
  'tpa',
  'international',
  'about',
  'overview',
  'news',
  'article',
  'health-library',
  'blog',
  'testimonial',
  'visiting',
  'visitor',
  'contact',
  'emergency',
  'policy',
  'policies',
];

export const BLOCKED_PATH_PATTERNS = [
  /\/login/i,
  /\/signin/i,
  /\/sign-in/i,
  /\/signup/i,
  /\/register/i,
  /\/password/i,
  /\/portal/i,
  /\/mychart/i,
  /\/patient-portal/i,
  /\/my-account/i,
  /\/dashboard/i,
  /\/admin/i,
  /\/wp-admin/i,
  /\/wp-login/i,
  /\/checkout/i,
  /\/payment/i,
  /\/pay\b/i,
  /\/cart/i,
  /\/search\b/i,
  /[?&]s=/i,
  /[?&]utm_/i,
  /\/doctor/i,
  /\/doctors/i,
  /\/physician/i,
  /\/consultants?\b/i,
  /\/our-doctors/i,
  /\/find-a-doctor/i,
  /\/book-appointment/i,
  /\/appointment/i,
  /\/slot/i,
  /\/career/i,
  /\/jobs?\b/i,
  /\/cdn-cgi\//i,
  /\/stakeholder/i,
  /\/investor/i,
  /\/csr-/i,
  /\/academics/i,
];

export const ASSET_EXTENSIONS = [
  '.jpg',
  '.jpeg',
  '.png',
  '.gif',
  '.webp',
  '.svg',
  '.pdf',
  '.mp4',
  '.mp3',
  '.zip',
  '.css',
  '.js',
  '.woff',
  '.woff2',
  '.ico',
];

export const NOISE_PHRASES = [
  'read more',
  'click here',
  'contact us today',
  'learn more',
  'book now',
  'know more',
  'view all',
  'see all',
  'cookie',
  'privacy policy',
  'terms of use',
];

/**
 * High-confidence aliases only. Ambiguous names stay as extracted.
 */
export const NAME_ALIASES: Record<string, string> = {
  cardiology: 'Cardiology',
  'cardiac sciences': 'Cardiology',
  'heart sciences': 'Cardiology',
  'department of cardiac sciences': 'Cardiology',
  'cardiology department': 'Cardiology',
  'heart & vascular': 'Cardiology',
  'heart and vascular': 'Cardiology',
  orthopaedics: 'Orthopaedics',
  orthopedics: 'Orthopaedics',
  'bone & joint': 'Orthopaedics',
  'bone and joint': 'Orthopaedics',
  'ortho': 'Orthopaedics',
  neurology: 'Neurology',
  neurosciences: 'Neurology',
  'neuro sciences': 'Neurology',
  oncology: 'Oncology',
  'cancer care': 'Oncology',
  'medical oncology': 'Oncology',
  gastroenterology: 'Gastroenterology',
  'gastro sciences': 'Gastroenterology',
  nephrology: 'Nephrology',
  'kidney care': 'Nephrology',
  urology: 'Urology',
  paediatrics: 'Paediatrics',
  pediatrics: 'Paediatrics',
  'child care': 'Paediatrics',
  gynaecology: 'Gynaecology',
  gynecology: 'Gynaecology',
  'obstetrics & gynaecology': 'Gynaecology',
  'obstetrics and gynecology': 'Gynaecology',
  dermatology: 'Dermatology',
  'skin care': 'Dermatology',
  pulmonology: 'Pulmonology',
  'respiratory medicine': 'Pulmonology',
  'chest medicine': 'Pulmonology',
  endocrinology: 'Endocrinology',
  rheumatology: 'Rheumatology',
  psychiatry: 'Psychiatry',
  'mental health': 'Psychiatry',
  ophthalmology: 'Ophthalmology',
  'eye care': 'Ophthalmology',
  ent: 'ENT',
  'ear nose throat': 'ENT',
  dentistry: 'Dentistry',
  'dental care': 'Dentistry',
};
